import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import { ClerkProvider } from "@clerk/nextjs";
import QueryClientProvider from "./QueryClientProvider";
import { GlobalContextProvider } from "./context/GlobalContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryClientProvider>
      <ClerkProvider>
        <GlobalContextProvider>
          <html lang="en">
            <body>
              <NavBar />
              <main>{children}</main>
            </body>
          </html>
        </GlobalContextProvider>
      </ClerkProvider>
    </QueryClientProvider>
  );
}
