import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";

import QueryClientProvider from "./QueryClientProvider";
import { GlobalContextProvider } from "./context/GlobalContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider>
          <GlobalContextProvider>
            <NavBar />
            <main>{children}</main>
          </GlobalContextProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
